I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script files/1_bookstore.rpy", line 6, in script
    show bg bookstore night
Exception: Image 'bg bookstore' does not accept attributes 'night'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script files/1_bookstore.rpy", line 6, in script
    show bg bookstore night
  File "C:\Users\mcboots42\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\mcboots42\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\mcboots42\Downloads\renpy-8.2.0-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\mcboots42\Downloads\renpy-8.2.0-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\mcboots42\Downloads\renpy-8.2.0-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\mcboots42\Downloads\renpy-8.2.0-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg bookstore' does not accept attributes 'night'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.0.24012702
Three Peach Hill 1.0
Wed Nov 20 23:32:27 2024
